#!/usr/bin/env sh

if [[ "${BASH_SOURCE[0]}" == "${0}" ]]; then
    echo "The script ${BASH_SOURCE[0]} is intended to be sourced and not run directly."
    exit 1
fi

_BOLD_RED='\033[1;31m'
_BOLD_YELLOW='\033[1;33m'
_BOLD_GREEN='\033[1;32m'
_NO_COLOR='\033[0m'

_BOX_TOP_LEFT='╔'
_BOX_TOP_RIGHT='╗'
_BOX_BOTTOM_LEFT='╚'
_BOX_BOTTOM_RIGHT='╝'
_BOX_VERTICAL='║'
_BOX_HORIZONTAL='═'

_ROW_BULLET='*'
_LOG_SYMBOL='*'

_DEFAULT_MIN_WIDTH=40
_DEFAULT_PADDING=4

shldn_log_row() {
  local color="$1"
  local message="$2"

  if [ -n "$color" ]; then
    printf "${_ROW_BULLET} ${color}${_LOG_SYMBOL}${_NO_COLOR}\t%s\n" "${message}"
  else
    printf "${_ROW_BULLET}\t%s\n" "${message}"
  fi
}

shldn_log_info_row() {
  shldn_log_row "" "$1"
}

shldn_log_success_row() {
  shldn_log_row "${_BOLD_GREEN}" "$1"
}

shldn_log_warn_row() {
  shldn_log_row "${_BOLD_YELLOW}" "$1"
}

shldn_log_error_row() {
  shldn_log_row "${_BOLD_RED}" "$1"
}

shldn_log_empty_row() {
  shldn_log_info_row
}

shldn_print_header() {
  local header_text="$1"
  local padding=$(printf '%0.s ' $(seq 1 $_DEFAULT_PADDING))
  local header_with_padding=" ${padding}${header_text}${padding} "

  local header_length=${#header_with_padding}
  local border_length=$([ $header_length -gt $_DEFAULT_MIN_WIDTH ] && echo "$header_length" || echo "$_DEFAULT_MIN_WIDTH")

  local top_border="${_BOX_TOP_LEFT}$(printf "${_BOX_HORIZONTAL}%.0s" $(seq 1 $((border_length-2))))${_BOX_TOP_RIGHT}"
  local bottom_border="${_BOX_BOTTOM_LEFT}$(printf "${_BOX_HORIZONTAL}%.0s" $(seq 1 $((border_length-2))))${_BOX_BOTTOM_RIGHT}"

  echo "$top_border"
  printf "${_BOX_VERTICAL}%-${border_length}s${_BOX_VERTICAL}\n"
  printf "${_BOX_VERTICAL}%-${border_length}s${_BOX_VERTICAL}\n" "$header_with_padding"
  printf "${_BOX_VERTICAL}%-${border_length}s${_BOX_VERTICAL}\n"
  echo "$bottom_border"
}

shldn_print_footer() {
  shldn_log_empty_row
  printf "%s\n\n" "******* END *******"
}